version: '3.1'

services:
  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_admin
      MYSQL_PASSWORD_FILE: /run/secrets/db_password

    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

secrets:
  db_password:
    file: secret-mysql-pass.txt
  db_root_password:
    file: secret-mysql-root-pass.txt
